"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.implant import Implant
globals()['Implant'] = Implant
from moonshine.model.implants_page import ImplantsPage


class TestImplantsPage(unittest.TestCase):
    """ImplantsPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImplantsPage(self):
        """Test ImplantsPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImplantsPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
