"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.service import Service
globals()['Service'] = Service
from moonshine.model.services_page import ServicesPage


class TestServicesPage(unittest.TestCase):
    """ServicesPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServicesPage(self):
        """Test ServicesPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServicesPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
