"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.argument import Argument
from moonshine.model.job_status_int32 import JobStatusInt32
from moonshine.model.job_success_int32 import JobSuccessInt32
globals()['Argument'] = Argument
globals()['JobStatusInt32'] = JobStatusInt32
globals()['JobSuccessInt32'] = JobSuccessInt32
from moonshine.model.job import Job


class TestJob(unittest.TestCase):
    """Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJob(self):
        """Test Job"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Job()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
