"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.task_status_int32 import TaskStatusInt32


class TestTaskStatusInt32(unittest.TestCase):
    """TaskStatusInt32 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskStatusInt32(self):
        """Test TaskStatusInt32"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskStatusInt32()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
