"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.task_success_int32 import TaskSuccessInt32


class TestTaskSuccessInt32(unittest.TestCase):
    """TaskSuccessInt32 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskSuccessInt32(self):
        """Test TaskSuccessInt32"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskSuccessInt32()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
