"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.argument import Argument
globals()['Argument'] = Argument
from moonshine.model.service import Service


class TestService(unittest.TestCase):
    """Service unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testService(self):
        """Test Service"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Service()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
