"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.job_status_int32 import JobStatusInt32


class TestJobStatusInt32(unittest.TestCase):
    """JobStatusInt32 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobStatusInt32(self):
        """Test JobStatusInt32"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobStatusInt32()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
