"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.listener import Listener
globals()['Listener'] = Listener
from moonshine.model.listeners_page import ListenersPage


class TestListenersPage(unittest.TestCase):
    """ListenersPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListenersPage(self):
        """Test ListenersPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListenersPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
