"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.task_status_int32 import TaskStatusInt32
from moonshine.model.task_success_int32 import TaskSuccessInt32
globals()['TaskStatusInt32'] = TaskStatusInt32
globals()['TaskSuccessInt32'] = TaskSuccessInt32
from moonshine.model.task import Task


class TestTask(unittest.TestCase):
    """Task unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTask(self):
        """Test Task"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Task()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
