"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.argument import Argument


class TestArgument(unittest.TestCase):
    """Argument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArgument(self):
        """Test Argument"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Argument()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
