"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.argument import Argument
globals()['Argument'] = Argument
from moonshine.model.listener import Listener


class TestListener(unittest.TestCase):
    """Listener unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListener(self):
        """Test Listener"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Listener()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
