"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.command import Command


class TestCommand(unittest.TestCase):
    """Command unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommand(self):
        """Test Command"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Command()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
