"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.architecture_string import ArchitectureString


class TestArchitectureString(unittest.TestCase):
    """ArchitectureString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArchitectureString(self):
        """Test ArchitectureString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ArchitectureString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
