"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.artifact_type_string import ArtifactTypeString


class TestArtifactTypeString(unittest.TestCase):
    """ArtifactTypeString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArtifactTypeString(self):
        """Test ArtifactTypeString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ArtifactTypeString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
