"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import moonshine
from moonshine.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_command_job(self):
        """Test case for command_job

        Send a Command to a Job  # noqa: E501
        """
        pass

    def test_create_job_for_implant(self):
        """Test case for create_job_for_implant

        Create Job For Implant  # noqa: E501
        """
        pass

    def test_create_listener(self):
        """Test case for create_listener

        Create Listener  # noqa: E501
        """
        pass

    def test_create_service(self):
        """Test case for create_service

        Create Service  # noqa: E501
        """
        pass

    def test_create_task_for_implant(self):
        """Test case for create_task_for_implant

        Create Task For Implant  # noqa: E501
        """
        pass

    def test_delete_implant(self):
        """Test case for delete_implant

        Delete Implant  # noqa: E501
        """
        pass

    def test_delete_listener(self):
        """Test case for delete_listener

        Delete Listener  # noqa: E501
        """
        pass

    def test_delete_service(self):
        """Test case for delete_service

        Delete Service  # noqa: E501
        """
        pass

    def test_download_implant(self):
        """Test case for download_implant

        Download implant artifact  # noqa: E501
        """
        pass

    def test_get_implant(self):
        """Test case for get_implant

        Get Implant by Id  # noqa: E501
        """
        pass

    def test_get_implants(self):
        """Test case for get_implants

        Get Implants  # noqa: E501
        """
        pass

    def test_get_job(self):
        """Test case for get_job

        Get Job by Id  # noqa: E501
        """
        pass

    def test_get_jobs_for_implant(self):
        """Test case for get_jobs_for_implant

        Get Jobs for Implant  # noqa: E501
        """
        pass

    def test_get_jobs_for_implant_with_status(self):
        """Test case for get_jobs_for_implant_with_status

        Get Jobs for Implant By Status  # noqa: E501
        """
        pass

    def test_get_listener(self):
        """Test case for get_listener

        Get Listener by Id  # noqa: E501
        """
        pass

    def test_get_listeners(self):
        """Test case for get_listeners

        Get Listeners  # noqa: E501
        """
        pass

    def test_get_service(self):
        """Test case for get_service

        Get Service by Id  # noqa: E501
        """
        pass

    def test_get_services(self):
        """Test case for get_services

        Get Services  # noqa: E501
        """
        pass

    def test_get_task(self):
        """Test case for get_task

        Get Task by Id  # noqa: E501
        """
        pass

    def test_get_tasks_for_implant(self):
        """Test case for get_tasks_for_implant

        Get Tasks for Implant  # noqa: E501
        """
        pass

    def test_get_tasks_for_implant_with_status(self):
        """Test case for get_tasks_for_implant_with_status

        Get Tasks for Implant By Status  # noqa: E501
        """
        pass

    def test_start_listener(self):
        """Test case for start_listener

        Start Listener by Id  # noqa: E501
        """
        pass

    def test_start_service(self):
        """Test case for start_service

        Start Service by Id  # noqa: E501
        """
        pass

    def test_stop_job(self):
        """Test case for stop_job

        Stop Job by Id  # noqa: E501
        """
        pass

    def test_stop_listener(self):
        """Test case for stop_listener

        Stop Listener by Id  # noqa: E501
        """
        pass

    def test_stop_service(self):
        """Test case for stop_service

        Stop Service by Id  # noqa: E501
        """
        pass

    def test_websocket(self):
        """Test case for websocket

        """
        pass


if __name__ == '__main__':
    unittest.main()
