"""
    Moonshine Server

    Management REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import moonshine
from moonshine.model.job import Job
globals()['Job'] = Job
from moonshine.model.jobs_page import JobsPage


class TestJobsPage(unittest.TestCase):
    """JobsPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobsPage(self):
        """Test JobsPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobsPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
