#ifndef CONTAINERC2_IMPLANT_CONFIG_H_
#define CONTAINERC2_IMPLANT_CONFIG_H_

#define DEFAULT_DWELL_PERIOD   15
#define DWELL_VARIATION_LOWER 0.9
#define DWELL_VARIATION_UPPER 1.1

#endif //CONTAINERC2_IMPLANT_CONFIG_H_
